RazorPagesGeneral/Pages/Employees/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;
using RazorPages.Services;

namespace RazorPages.General.Pages.Employees
{
    public class DeleteModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public DeleteModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        [BindProperty]
        public Employee Employe { get; set; }
        public IActionResult OnGet(int id)
        {
            Employe = _employeeRepository.GetEmployee(id);

            if (Employe == null)
                return RedirectToPage("/NotFound");

            return Page();
        }

        public IActionResult OnPost()
        {
            Employee deleteEmploye = _employeeRepository.Delete(Employe.Id);

            if (deleteEmploye.PhotoPath != null)
            {
                string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", deleteEmploye.PhotoPath);

                if (deleteEmploye.PhotoPath != "noimage.png")
                    System.IO.File.Delete(filePath);
            }

            if (deleteEmploye == null)
                return RedirectToPage("/NotFound");

            return RedirectToPage("Employes");
        }
    }
}

RazorPagesGeneral/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;
using RazorPages.Services;

namespace RazorPages.General.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        public Employee Employee { get; private set; }

        public DetailsModel(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public IActionResult OnGet(int Id)
        {
            Employee = _employeeRepository.GetEmployee(Id);

            if (Employee == null)
                return RedirectToPage("/NotFound");

            return Page();
        }
    }
}

RazorPagesGeneral/Pages/Employees/Employes.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPages.Models;
using RazorPages.Services;

namespace RazorPagesGeneral.Pages.Employes
{
    public class EmployesModel : PageModel
    {
        private readonly IEmployeeRepository _db;
        public IEnumerable<Employee> Employee { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        public EmployesModel(IEmployeeRepository db)
        {
            _db = db;
        }

        public void OnGet()
        {
            Employee = _db.Search(SearchTerm);
        }
    }
}

RazorPagesGeneral/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesGeneral/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string Message { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Message = $"Welcome to Russia!\nThe Date {DateTime.Now.ToLongTimeString()}";
        }
    }
}

RazorPagesGeneral/Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPages.General.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPagesGeneral/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesGeneral/ViewCopmonents/HedCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RazorPages.Models;
using RazorPages.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPages.General.ViewCopmonents
{
    public class HedCountViewComponent : ViewComponent
    {
        private readonly IEmployeeRepository _employeeRepository;

        public HedCountViewComponent(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public IViewComponentResult Invoke(Dept? department = null)
        {
            var result = _employeeRepository.EmployeCountByDept(department);
            return View(result);
        }
    }
}

RazorPagesGeneral/Pages/Employees/Delete.cshtml
@page "{id}"
@model RazorPages.General.Pages.Employees.DeleteModel
@{
    ViewData["Title"] = "Удалить";
    ViewData["ShowButtons"] = false;
}

<h1 class="text-center">Подтверждение удаления</h1>

<div class="alert alert-danger">
    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <partial name="_DisplayEmployeePartial" model="Model.Employe" view-data="ViewData" />
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6 col-xl-4 offset-sm-0 offset-md-3 offset-xl-4">
            <div class="text-center text-secondary">
                <h4>Id работника: <span class="text-primary">@Model.Employe.Id</span></h4><hr />
                <h4>Email работника: <span class="text-primary">@Model.Employe.Email</span></h4><hr />
                <h4>Департамент: <span class="text-primary">@Model.Employe.Departament</span></h4><hr />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h5>Вы уверены, что хотите удалить данные - @Model.Employe.Name?</h5>

            <form method="post">
                <button type="submit" class="btn btn-danger">Да</button>
                <a class="btn btn-success" asp-page="/Employees/Employes">Нет</a>
            </form>
        </div>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Details.cshtml
@page "{id}"
@model RazorPages.General.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = "Details";
    var photoParth = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";
}

<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        @*@await Component.InvokeAsync("HedCount", new { department = Model.Employee.Departament })*@    
        <vc:hed-count department="@Model.Employee.Departament"></vc:hed-count>
    </div>
</div>

<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        <div class="card cardBoxShadow">

            <div class="card-header cardHeaderStyle text-center">
                <h1>@Model.Employee.Name</h1>
            </div>

            <div class="card-body cardBoxShadow">
                <div class="row">
                    <div class="col col-lg-9">
                        <h4 class="cardTextLeftFloating">Id работника : @Model.Employee.Id</h4><hr />
                        <h4 class="cardTextLeftFloating">Email : @Model.Employee.Email</h4><hr />
                        <h4 class="cardTextLeftFloating">Департамент : <span class="text-danger font-weight-bold">@Model.Employee.Departament</span></h4><hr />
                    </div>
                    <div class="col col-lg-3">
                        <div style="border-right: 1px solid rgba(0,0,0,.1);">
                            <img class="card-img-top imageThumbnail border border-primary" style="background-color: #dle7ff;" src="@photoParth" asp-append-version="true" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col">
                        <div class="card-footer text-center" style="background-color: rgba(0,0,0,0.25);">
                            <a asp-page="Employes" class="btn btn-success buttonShadow">Назад</a>
                            <a href="#" class="btn btn-primary buttonShadow">Изменить</a>
                            <a href="#" class="btn btn-danger buttonShadow">Удалить</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Edit.cshtml
@page "{id:min(1)?}/{handler?}"
@model RazorPages.General.Pages.Employees.EditModel
@{
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";

    var pageTitle = Model.Employee.Id < 0 ? "Изменить" : "Добавить";
    ViewData["Title"] = "pageTitle";
}

<form method="post" asp-page-handler="UpdateNotificationReferences">
    <div class="row text-center notifyBlock">
        <div class="col form-check">
            <h1>Ссылка.</h1>
            <input asp-for="Notify" class="form-check-input" />
            <label asp-for="Notify" class="form-check-label">
                ОТправлять сообщение на почту , при изменении данных
            </label><br />

            <button type="submit" class="btn btn-primary text-center">Отправить</button>

            @if (!string.IsNullOrWhiteSpace(Model.Message))
            {
                <div class="alert alert-success">
                    <p class="p-3 mt-2">@Model.Message</p>
                </div>
            }
        </div>
    </div>
</form>
<hr />

<div asp-validation-summary="All" class="text-danger text-center"></div>

<!--Создаём форму редактирования-->
<form method="post" asp-page-handler="OnPost" class="mt-3" enctype="multipart/form-data">
    <!--Создаём скрытое поле для параметра ID-->
    <input type="hidden" asp-for="Employee.Id" />
    <input type="hidden" asp-for="Employee.PhotoPath" />

    <!--Добавляем поля редактирования-->
    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card cardBoxShadow">
                <div class="card-header cardHeaderStyle text-center">
                    <!--Добавляем поле редактирования имени-->
                    <div class="form-group row">
                        <label asp-for="Employee.Name" class="col col-lg-4 col-form-label text-right">Изменить имя:</label>
                        <div class="col col-lg-6">
                            <input asp-for="Employee.Name" class="form-control" placeholder="@Model.Employee.Name" />
                            <!--Добавляем сообщение валидации формы-->
                            <span asp-validation-for="Employee.Name" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body cardBodyStyle text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4 class="cardTextLeftFloating">ID работника: @Model.Employee.Id</h4><hr />

                            <!--Добавляем поле редактирования e-mail-->
                            <div class="form-group row">
                                <label asp-for="Employee.Email" class="col col-lg-4 col-form-label text-right">Изменить E-mail:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Employee.Email" class="form-control mr-2" placeholder="@Model.Employee.Email" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Employee.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                            <!--Добавляем поле редактирования департамента-->
                            <div class="form-group row">
                                <label asp-for="Employee.Departament" class="col col-lg-4 col-form-label text-right">Изменить Департамент:</label>
                                <div class="col-12 col-lg-6">
                                    <!--Создаём выпадающий список с департаментами-->
                                    <!--Необходимо подключить класс локально или глобально-->
                                    <select asp-for="Employee.Departament" class="custom-select mr-2" asp-items="Html.GetEnumSelectList<Dept>()">
                                        <!--Добавляем начальный элемент выпадающего списка-->
                                        <option value="">Выберите департамент</option>
                                    </select>
                                    <span asp-validation-for="Employee.Departament" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div class="col col-lg-3">
                            <div>
                                <img class="card-img-top imageThumbnail border border-primary" src="@photoPath" asp-append-version="true" />

                                <div class="custom-file">
                                    <input asp-for="Photo" class="custom-file-input form-control" />
                                    <label class="custom-file-label text-left ">+</label>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <button type="submit" class="btn btn-success buttonShadow">Изменить</button>
                                <a asp-page="index" class="btn btn-danger buttonShadow">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section Scripts  {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

        <partial name="_ValidationScriptsPartial" />
    }

</form>

RazorPagesGeneral/Pages/Employees/Employes.cshtml
@page
@model RazorPagesGeneral.Pages.Employes.EmployesModel
@{
    ViewData["Title"] = "Employes";
    ViewData["ShowButtons"] = true;
}

@if (TempData["SeccessMessage"] != null)
{
    <div class="alert alert-success text-center">
        @TempData["SeccessMessage"]
    </div>
}

<form method="get" class="mb-3">
    <div class="input-group">
        <input class="form-control" asp-for="SearchTerm" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Поиск</button>
        </div>
    </div>
</form>

@*@await Component.InvokeAsync("HedCount")*@
<vc:hed-count department="@null"></vc:hed-count>

<h1>Employes</h1>

<div class="row">
    @foreach (var item in Model.Employee)
    {
        <div class="col-12 col-sm-6 col-lg-4">
            <partial name="_DisplayEmployeePartial" model="item" view-data="ViewData"/>
        </div>
    }
</div>

RazorPagesGeneral/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="row text-center">
    <div class="col">
        <h1>Welcome</h1>
        <h2>to aour Store project.</h2>
    </div>
</div>

<div class="row text-center">
    <div class="col">
        <img src="~/images/Main.Store.jpg" class="w-80 img-fluid img-thumbnail" alt="Sore Main"/>
    </div>
</div>

RazorPagesGeneral/Pages/NotFound.cshtml
@page
@model RazorPages.General.Pages.NotFoundModel
@{
    ViewData["Title"] = "Not Found";
}

<div class="row">
    <div class="col text-center">
        <img src="~/images/NotFound.png" alt="Page Not Found" />
    </div>
</div>

<div class="row">
    <div class="col text-center">
        <h1>The resource you are looking for cannot be found!</h1>
        <a asp-page="/Employees/Employes" class="btn btn-primary">Вернутьcя на страницу с персоналом.</a>
    </div>
</div>

RazorPagesGeneral/Pages/Shared/Components/HedCount/Default.cshtml
@model IEnumerable<DeptHeadCount>

<table class="table table-hover rounded-pill">
    <thead class="thead-light">
        <tr>
            <th>Департамент</th>
            <th>Количество</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Department</td>
                <td>@item.Count</td>
            </tr>
        }
    </tbody>
</table>

RazorPagesGeneral/Pages/Shared/_DisplayEmployeePartial.cshtml
@model Employee

@{
    var photoParth = $"/images/{Model.PhotoPath ?? "noimage.png"}";
    var ShowButtons = (bool)ViewData["ShowButtons"];

}

@*выствялем для разных дисплеев*@
<div class="card-deck">
    <div class="card m-3 cardBoxShadow">
        <div class="card-header text-center cardHeaderStyle">
            <h3>@Model.Name</h3>
        </div>

        <div class="text-center cardBodyStyle">
            <img class="card-img-top imageThumbnail" src="@photoParth" asp-append-version="true" />
        </div>

        @if (ShowButtons)
        {
            <divc class="card-footer text-center">
                <a asp-page="/Employees/Details" asp-route-Id="@Model.Id" class="btn btn-success m-1 buttonShadow">Просмотреть</a>
                <a asp-page="/Employees/Edit" asp-route-Id="@Model.Id" class="btn btn-primary m-1 buttonShadow">Изменить</a>
                <a asp-page="/Employees/Delete" asp-route-Id="@Model.Id" class="btn btn-danger m-1 buttonShadow">Удалить</a>
            </divc>
        }
    </div>
</div>

RazorPagesGeneral/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPagesGeneral</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 menuBg">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-page="/Index">
                    <img src="~/images/BannerStore.jpg" alt="Store"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Index">Домашная страница</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Employees/Employes">Работники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Employees/Edit">Добавить работника</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container containerBordered">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container border">
            &copy; 2021 - Store - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>